config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get 'sessions/new'
  get 'users/new'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, :user_mod
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :user_mods
    has_many :mods, through: :user_mods
    
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    
    def self.search(name)
        if name.match(/\A[+-]?\d+?(\.\d+)?\Z/) == nil
            name.downcase!
            where('LOWER(name) LIKE ?', "%#{name}%")
        else
            where('id = ?', name.to_f)
        end
    end
    
    def fullname
      "#{name} #{surname}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show, :index]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :lecturer_or_admin, only: [:index]
  
  def index
       @users = User.search(params[:search])
  end
  
  
  def edit
  end
  

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  
  def show
    @user = User.find(params[:id])
    @mods = Mod.all
    @user_mods = @user.user_mods
  end
  
  
  def new
    @user = User.new
  end
  
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "User created successfully"
      redirect_to login_url
    else
      render 'new'
    end
  end
  

  private

    def user_params
      params.require(:user).permit(:name, :surname, :email, :role, :password,
                                   :password_confirmation)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms a lecturer or admin user.
    def lecturer_or_admin
      unless is_lecturer? || is_admin?
        flash[:danger] = "You must be a lecturer or administrator to use the search functionality"
        redirect_to user_path(:id => current_user.id)
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
        redirect_to user_path(:id => current_user.id) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    # Returns the Gravatar for the give user.
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/_form.html.erb
<%= form_for(usermod) do |f| %>
  <% if usermod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "Search Results") %>
    
    <div class="panel panel-default">
        <div class="panel-heading">SEARCH RESULTS</div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
                
                <% @users.where(role: "Student").each do |user| %>
                    <table class="table">
                        <h2><%= user.name.humanize %> <%= user.surname.humanize %>'s Modules</h2>
                        <tr>
                            <th>Module id</th>
                            <th>Module name</th>
                            <th>Enrollment Date</th>
                            <th>Grade Deadline</th>
                            <th colspan="3">Grade</th>
                        </tr>
                        
                        <% user.user_mods.each do |usermod| %>
                        <tr>
                            <td><%= usermod.mod.id %></td>
                            <td><%= usermod.mod.name %></td>
                            <td><%= usermod.created_at.strftime("%b-%d-%Y") %></td>
                            <td><%= Time.at(1496307600).strftime("%b-%d-%Y") %></td>
                            <td>
                                <% if usermod.grade.nil? %>
                                TBC
                                <% else %>
                                <%= usermod.grade %>%
                                <% end %>
                            </td>
                            
                            <% if is_lecturer? %>
                                <% current_user.user_mods.each do |lecmod| %>
                                    <% if lecmod.mod_id == usermod.mod_id %>
                                            <td>
                                                <%= form_for UserMod.find(usermod.id), :html => {:class => "form-inline"}, :method => :PUT do |f| %>
                                                
                                                    <%= f.text_field :grade, :value => usermod.grade, class: 'form-control col-xs-1' %>
                                            </td>
                                            <td>
                                                    <%= f.submit "Update Grade", class: "btn btn-primary btn-sm" %>
                                                <% end %>
                                            </td>
                                    <% end %>
                                <% end %>
                            <% end %>
                            
                        </tr>
                        <% end %>
                    </table><br/><br/>
                <% end %>
            </div>
        </div>
    </div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Create New User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :surname %>
      <%= f.text_field :surname, class: 'form-control' %>

      <%= f.label :role %>
      <%= f.select :role, options_for_select([['Admin'], ['Lecturer'], ['Student']]), {}, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create User", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<p>
    <% if is_admin? %>
        <%= render 'shared/admin_dash' %>
    <% elsif is_lecturer? %>
        <%= render 'shared/lecturer_dash' %>
    <% elsif is_student? %>
        <%= render 'shared/student_dash' %>
    <% else %>
        Who the hell are you?
    <% end %>
</p>