config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get 'sessions/new'
  get 'users/new'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, :user_mod
end

app/views/shared/_admin_dash.html.erb
<div>
  <h1><%= @user.name.humanize %> <%= @user.surname.humanize %>'s Admin Dashboard</h1>
    <div class="panel panel-default">
      <div class="panel-heading">MODULE ASSIGNMENT</div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
            
              <%= form_for(UserMod.new, url: user_mod_index_path) do |f| %>
                
                <label for="user_id">Select Lecturer</label>
                <%= f.collection_select :user_id, User.where(role: "Lecturer"), :id, :fullname, {required: true}, {class: "form-control"} %>
                
                <label for="mod_id">Select Module</label>
                <%= f.collection_select :mod_id, Mod.all, :id, :name, {required: true}, {class: "form-control"} %>
                
                <%= f.submit "Assign", class: "btn btn-primary" %>
              <% end %>
          </div>
      </div>
    </div>
    
    <%= render 'shared/search' %>
</div>

app/views/shared/_admin_usermod.html.erb
<tr>
  <th>id</th>
  <th>module</th>
  <th>enrollment date</th>
  <th>grade</th>
  <th></th>
</tr>
<% @user_mods.each do |usermod| %>
  <tr>
    <td><%= usermod.id %></td>
    <td><%= usermod.mod.name %></td>
    <td><%= usermod.created_at.strftime("%b-%d-%Y") %></td>
    <td>%</td>
    <td>
      <%= button_to "WITHDRAW", {:controller => :user_mod, :action => 'destroy', :id => usermod.id }, :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-primary btn-sm' %>
    </td>
  </tr>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_lecturer_dash.html.erb
<div>
  <h1><%= @user.name.humanize %> <%= @user.surname.humanize %>'s Lecturer Dashboard</h1>
    
    <div class="panel panel-default">
      <div class="panel-heading">ASSIGNED MODULES</div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
            <% if @user.user_mods.any? %>
              <table class="table">
                <%= render 'shared/lecturer_usermod' %>
              </table>
            <% end %>
          </div>
        </div>
      </div>
      
      <%= render 'shared/search' %>
    
</div>

app/views/shared/_lecturer_usermod.html.erb
<tr>
  <th>id</th>
  <th>module</th>
  <th>assignment date</th>
  <th>grade deadline date</th>
</tr>
<% @user_mods.each do |usermod| %>
  <tr>
    <td><%= usermod.id %></td>
    <td><%= usermod.mod.name %></td>
    <td><%= usermod.created_at.strftime("%b-%d-%Y") %></td>
    <td><%= Time.at(1496307600).strftime("%b-%d-%Y") %></td>
  </tr>
<% end %>

app/views/shared/_search.html.erb
<div class="panel panel-default">
  <div class="panel-heading">STUDENT SEARCH</div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
        <%= form_tag users_path, :method => 'get', :id => 'users_search' do %>
          <p>
              <label for="search">Enter Student ID or First Name</label>
              <%= text_field_tag :search, params[:search], class: 'form-control' %>
              <%= submit_tag "Search", :name => nil, class: 'btn btn-primary' %>
          </p>
        <% end %>
      </div>
    </div>
</div>

app/views/shared/_student_dash.html.erb
<div>
  <h1><%= @user.name.humanize %> <%= @user.surname.humanize %>'s Student Dashboard</h1>

    <% 
      @modPassCount = 0 
      @passGrade = false
      @accumPassMark = 0
      @maxCompMark = 0
      @passByCompCandidate = false
      @passByComp = false
      @topmark1 = 0
      @topmark2 = 0
      @topmark3 = 0
      @avgMark = 0
    %>
  
    <% @user_mods.each do |usermod| %>
    
      <!-- Capture three top marks -->
      <%
      if usermod.grade.to_f > @topmark1
        @topmark3 = @topmark2
        @topmark2 = @topmark1
        @topmark1 = usermod.grade
      elsif usermod.grade.to_f > @topmark2
        @topmark3 = @topmark2
        @topmark2 = usermod.grade
      elsif usermod.grade.to_f > @topmark3
        @topmark3 = usermod.grade
      end
      %>
      
      <!-- Capture number of modules passed and accumulated value -->
      <%
      if usermod.grade.to_f>=40 
        @modPassCount = @modPassCount +1
        @accumPassMark = @accumPassMark + usermod.grade
      end
      %>
      
      <!-- Determine pass and pass by compensation mark -->
      <%
      if @modPassCount >= 3
        @passGrade = true
      elsif @modPassCount < 3 && @modPassCount >= 2
        @passByCompCandidate = true
        @user_mods.each do |usermod2|
          if usermod2.grade.to_f >= 35 && usermod2.grade.to_f < 40 && usermod2.grade.to_f > @maxCompMark
            @maxCompMark = @maxCompMark + usermod2.grade
          end
        end
      end
      %>
    <% end %>
    
    <!-- Determine pass by comp -->
    <%
    if !@passGrade && @passByCompCandidate && ((40-@maxCompMark.to_f)*2) < (@accumPassMark.to_f - 80)
      @passByComp = true
    end
    %>
    
    <% @avgMark = ((@topmark1 + @topmark2 + @topmark3)/3) %>

    <h1>
      Grade:
      <% if @passGrade || @passByComp %>
        <% if @avgMark.to_f >= 70 %>
          Disctinction
        <% elsif @avgMark.to_f >= 60 %>
          Merit upper division
        <% elsif @avgMark.to_f >= 50 %>
          Merit lower division
        <% elsif @avgMark.to_f >= 40 %>
          Pass
        <% end %>
        <% if @passByComp %>
          (by Compensation)
        <% end %>
      <% else %>
        Fail
      <% end %>
    </h1>
    <h2>
      <% if current_time < grading_deadline %>
        Note: Not Final grade, final grade will be published after deadline (<%= grading_deadline %>)
      <% else %>
        (Final Grade)
      <% end %>
    </h2>
    
    <!-- uncomment for troubleshooting, should prob move to log -->
    <!--
      @modPassCount: <%= @modPassCount %> <br/>
      @passGrade: <%= @passGrade %> <br/>
      @accumPassMark: <%= @accumPassMark %> <br/>
      @maxCompMark: <%=  @maxCompMark %> <br/>
      @passByComp: <%= @passByComp %> <br/>
      @topmark1: <%= @topmark1 %> <br/>
      @topmark2: <%= @topmark2 %> <br/>
      @topmark3: <%= @topmark3 %> <br/>
      @avgMark: <%= @avgMark %> <br/>
    -->
    <!-- end uncomment for troubleshooting -->
    
    <div class="panel panel-default">
      <div class="panel-heading">MODULE ENROLLMENT</div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
            
              <%= form_for(UserMod.new, url: user_mod_index_path) do |f| %>
              
                <%= f.hidden_field :user_id, :value => @user.id %>
                <%= f.collection_select :mod_id, Mod.all, :id, :name, {prompt: "Select a module"}, {class: "form-control"} %>
    
                <%= f.submit "Enroll", class: "btn btn-primary" %>
              <% end %>
          </div>
      </div>
    </div>
    
    <div class="panel panel-default">
      <div class="panel-heading">CURRENT MODULES</div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
            <% if @user.user_mods.any? %>
              <table class="table">
                <%= render 'shared/student_usermod' %>
              </table>
            <% end %>
          </div>
        </div>
      </div>
</div>

app/views/shared/_student_usermod.html.erb
<tr>
  <th>id</th>
  <th>module</th>
  <th>enrollment date</th>
  <th>grade</th>
  <th></th>
</tr>
<% @user_mods.each do |usermod| %>
  <tr>
    <td><%= usermod.id %></td>
    <td><%= usermod.mod.name %></td>
    <td><%= usermod.created_at.strftime("%b-%d-%Y") %></td>
    <td>
        <% if usermod.grade.nil? %>
          TBC
        <% else %>
          <%= usermod.grade %>% 
        <% end %>
    </td>
    <td>
      <%= button_to "WITHDRAW", {:controller => :user_mod, :action => 'destroy', :id => usermod.id }, :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-primary btn-sm' %>
    </td>
  </tr>
<% end %>