config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get 'sessions/new'
  get 'users/new'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, :user_mod
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Grading Application by Gareth O'Connor &amp; Shane Forbes<br/><br/>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Grading Application", root_path, :id => "logo" %>
    <nav>
        <% if logged_in? %>
          <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Dashboard", user_path(:id => current_user.id) %></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Log in", login_path %></li>
          </ul>
        <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
    <script src="//cdjns.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>